name: litelauncher
description: Minecraft Java Edition 启动器 for Android — Flutter + KSU + LWJGL3 + MobileGlues
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1

  # 模型
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # 依赖注入
  get_it: ^9.2.1

  # 函数式
  dartz: ^0.10.1
  rxdart: ^0.28.0

  # 平台
  pigeon: ^27.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

  # UI
  google_fonts: ^8.2.0
  url_launcher: ^6.3.1
  file_picker: ^11.0.2

  # 工具
  equatable: ^2.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 代码生成
  build_runner: ^2.4.14
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.9.3

  # 测试
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
