// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum AccountType {
  microsoft,
  offline,
  yggdrasil,
}

class VersionInfo {
  VersionInfo({
    required this.id,
    required this.type,
    required this.url,
    required this.releaseTime,
    required this.installed,
    this.loaderName,
  });

  String id;

  String type;

  String url;

  String releaseTime;

  bool installed;

  String? loaderName;

  List<Object?> _toList() {
    return <Object?>[
      id,
      type,
      url,
      releaseTime,
      installed,
      loaderName,
    ];
  }

  Object encode() {
    return _toList();  }

  static VersionInfo decode(Object result) {
    result as List<Object?>;
    return VersionInfo(
      id: result[0]! as String,
      type: result[1]! as String,
      url: result[2]! as String,
      releaseTime: result[3]! as String,
      installed: result[4]! as bool,
      loaderName: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VersionInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(url, other.url) && _deepEquals(releaseTime, other.releaseTime) && _deepEquals(installed, other.installed) && _deepEquals(loaderName, other.loaderName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VersionInfo(id: $id, type: $type, url: $url, releaseTime: $releaseTime, installed: $installed, loaderName: $loaderName)';
  }
}

class VersionDetail {
  VersionDetail({
    required this.id,
    required this.type,
    required this.mainClass,
    required this.assetsIndex,
    required this.javaVersion,
    required this.releaseTime,
    required this.size,
  });

  String id;

  String type;

  String mainClass;

  String assetsIndex;

  int javaVersion;

  String releaseTime;

  int size;

  List<Object?> _toList() {
    return <Object?>[
      id,
      type,
      mainClass,
      assetsIndex,
      javaVersion,
      releaseTime,
      size,
    ];
  }

  Object encode() {
    return _toList();  }

  static VersionDetail decode(Object result) {
    result as List<Object?>;
    return VersionDetail(
      id: result[0]! as String,
      type: result[1]! as String,
      mainClass: result[2]! as String,
      assetsIndex: result[3]! as String,
      javaVersion: result[4]! as int,
      releaseTime: result[5]! as String,
      size: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VersionDetail || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(mainClass, other.mainClass) && _deepEquals(assetsIndex, other.assetsIndex) && _deepEquals(javaVersion, other.javaVersion) && _deepEquals(releaseTime, other.releaseTime) && _deepEquals(size, other.size);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VersionDetail(id: $id, type: $type, mainClass: $mainClass, assetsIndex: $assetsIndex, javaVersion: $javaVersion, releaseTime: $releaseTime, size: $size)';
  }
}

class AccountInfo {
  AccountInfo({
    required this.id,
    required this.username,
    required this.uuid,
    required this.type,
    this.skinUrl,
    this.authServer,
  });

  String id;

  String username;

  String uuid;

  AccountType type;

  String? skinUrl;

  String? authServer;

  List<Object?> _toList() {
    return <Object?>[
      id,
      username,
      uuid,
      type,
      skinUrl,
      authServer,
    ];
  }

  Object encode() {
    return _toList();  }

  static AccountInfo decode(Object result) {
    result as List<Object?>;
    return AccountInfo(
      id: result[0]! as String,
      username: result[1]! as String,
      uuid: result[2]! as String,
      type: result[3]! as AccountType,
      skinUrl: result[4] as String?,
      authServer: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AccountInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(username, other.username) && _deepEquals(uuid, other.uuid) && _deepEquals(type, other.type) && _deepEquals(skinUrl, other.skinUrl) && _deepEquals(authServer, other.authServer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AccountInfo(id: $id, username: $username, uuid: $uuid, type: $type, skinUrl: $skinUrl, authServer: $authServer)';
  }
}

class AuthProgress {
  AuthProgress({
    required this.userCode,
    required this.verificationUri,
    required this.status,
    this.error,
  });

  String userCode;

  String verificationUri;

  String status;

  String? error;

  List<Object?> _toList() {
    return <Object?>[
      userCode,
      verificationUri,
      status,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static AuthProgress decode(Object result) {
    result as List<Object?>;
    return AuthProgress(
      userCode: result[0]! as String,
      verificationUri: result[1]! as String,
      status: result[2]! as String,
      error: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(userCode, other.userCode) && _deepEquals(verificationUri, other.verificationUri) && _deepEquals(status, other.status) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AuthProgress(userCode: $userCode, verificationUri: $verificationUri, status: $status, error: $error)';
  }
}

class GameConfig {
  GameConfig({
    required this.versionId,
    required this.gameDir,
    required this.javaHome,
    required this.maxRamMb,
    required this.renderMode,
    required this.loaderType,
    required this.extraJvmArgs,
  });

  String versionId;

  String gameDir;

  String javaHome;

  int maxRamMb;

  int renderMode;

  String loaderType;

  List<String> extraJvmArgs;

  List<Object?> _toList() {
    return <Object?>[
      versionId,
      gameDir,
      javaHome,
      maxRamMb,
      renderMode,
      loaderType,
      extraJvmArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GameConfig decode(Object result) {
    result as List<Object?>;
    return GameConfig(
      versionId: result[0]! as String,
      gameDir: result[1]! as String,
      javaHome: result[2]! as String,
      maxRamMb: result[3]! as int,
      renderMode: result[4]! as int,
      loaderType: result[5]! as String,
      extraJvmArgs: (result[6]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GameConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(versionId, other.versionId) && _deepEquals(gameDir, other.gameDir) && _deepEquals(javaHome, other.javaHome) && _deepEquals(maxRamMb, other.maxRamMb) && _deepEquals(renderMode, other.renderMode) && _deepEquals(loaderType, other.loaderType) && _deepEquals(extraJvmArgs, other.extraJvmArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GameConfig(versionId: $versionId, gameDir: $gameDir, javaHome: $javaHome, maxRamMb: $maxRamMb, renderMode: $renderMode, loaderType: $loaderType, extraJvmArgs: $extraJvmArgs)';
  }
}

class GameStatus {
  GameStatus({
    required this.state,
    required this.fps,
    required this.usedRamMb,
    this.crashReport,
  });

  int state;

  int fps;

  int usedRamMb;

  String? crashReport;

  List<Object?> _toList() {
    return <Object?>[
      state,
      fps,
      usedRamMb,
      crashReport,
    ];
  }

  Object encode() {
    return _toList();  }

  static GameStatus decode(Object result) {
    result as List<Object?>;
    return GameStatus(
      state: result[0]! as int,
      fps: result[1]! as int,
      usedRamMb: result[2]! as int,
      crashReport: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GameStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(fps, other.fps) && _deepEquals(usedRamMb, other.usedRamMb) && _deepEquals(crashReport, other.crashReport);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GameStatus(state: $state, fps: $fps, usedRamMb: $usedRamMb, crashReport: $crashReport)';
  }
}

class DownloadProgress {
  DownloadProgress({
    required this.taskId,
    required this.name,
    required this.progress,
    required this.downloadedBytes,
    required this.totalBytes,
    required this.speedBytesPerSec,
    required this.status,
  });

  String taskId;

  String name;

  double progress;

  int downloadedBytes;

  int totalBytes;

  int speedBytesPerSec;

  String status;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      name,
      progress,
      downloadedBytes,
      totalBytes,
      speedBytesPerSec,
      status,
    ];
  }

  Object encode() {
    return _toList();  }

  static DownloadProgress decode(Object result) {
    result as List<Object?>;
    return DownloadProgress(
      taskId: result[0]! as String,
      name: result[1]! as String,
      progress: result[2]! as double,
      downloadedBytes: result[3]! as int,
      totalBytes: result[4]! as int,
      speedBytesPerSec: result[5]! as int,
      status: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) && _deepEquals(name, other.name) && _deepEquals(progress, other.progress) && _deepEquals(downloadedBytes, other.downloadedBytes) && _deepEquals(totalBytes, other.totalBytes) && _deepEquals(speedBytesPerSec, other.speedBytesPerSec) && _deepEquals(status, other.status);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DownloadProgress(taskId: $taskId, name: $name, progress: $progress, downloadedBytes: $downloadedBytes, totalBytes: $totalBytes, speedBytesPerSec: $speedBytesPerSec, status: $status)';
  }
}

class DeviceInfo {
  DeviceInfo({
    required this.totalRamMb,
    required this.availableRamMb,
    required this.cpuModel,
    required this.coreCount,
    required this.gpuRenderer,
    required this.deviceTier,
    required this.isRooted,
    required this.hasKsuModule,
  });

  int totalRamMb;

  int availableRamMb;

  String cpuModel;

  int coreCount;

  String gpuRenderer;

  int deviceTier;

  bool isRooted;

  bool hasKsuModule;

  List<Object?> _toList() {
    return <Object?>[
      totalRamMb,
      availableRamMb,
      cpuModel,
      coreCount,
      gpuRenderer,
      deviceTier,
      isRooted,
      hasKsuModule,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceInfo decode(Object result) {
    result as List<Object?>;
    return DeviceInfo(
      totalRamMb: result[0]! as int,
      availableRamMb: result[1]! as int,
      cpuModel: result[2]! as String,
      coreCount: result[3]! as int,
      gpuRenderer: result[4]! as String,
      deviceTier: result[5]! as int,
      isRooted: result[6]! as bool,
      hasKsuModule: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(totalRamMb, other.totalRamMb) && _deepEquals(availableRamMb, other.availableRamMb) && _deepEquals(cpuModel, other.cpuModel) && _deepEquals(coreCount, other.coreCount) && _deepEquals(gpuRenderer, other.gpuRenderer) && _deepEquals(deviceTier, other.deviceTier) && _deepEquals(isRooted, other.isRooted) && _deepEquals(hasKsuModule, other.hasKsuModule);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceInfo(totalRamMb: $totalRamMb, availableRamMb: $availableRamMb, cpuModel: $cpuModel, coreCount: $coreCount, gpuRenderer: $gpuRenderer, deviceTier: $deviceTier, isRooted: $isRooted, hasKsuModule: $hasKsuModule)';
  }
}

class ModInfo {
  ModInfo({
    required this.fileName,
    required this.name,
    required this.version,
    required this.loaderType,
    required this.enabled,
    required this.size,
  });

  String fileName;

  String name;

  String version;

  String loaderType;

  bool enabled;

  int size;

  List<Object?> _toList() {
    return <Object?>[
      fileName,
      name,
      version,
      loaderType,
      enabled,
      size,
    ];
  }

  Object encode() {
    return _toList();  }

  static ModInfo decode(Object result) {
    result as List<Object?>;
    return ModInfo(
      fileName: result[0]! as String,
      name: result[1]! as String,
      version: result[2]! as String,
      loaderType: result[3]! as String,
      enabled: result[4]! as bool,
      size: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileName, other.fileName) && _deepEquals(name, other.name) && _deepEquals(version, other.version) && _deepEquals(loaderType, other.loaderType) && _deepEquals(enabled, other.enabled) && _deepEquals(size, other.size);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ModInfo(fileName: $fileName, name: $name, version: $version, loaderType: $loaderType, enabled: $enabled, size: $size)';
  }
}

class ModrinthProject {
  ModrinthProject({
    required this.id,
    required this.slug,
    required this.title,
    required this.description,
    required this.iconUrl,
    required this.downloads,
    required this.categories,
  });

  String id;

  String slug;

  String title;

  String description;

  String iconUrl;

  int downloads;

  List<String> categories;

  List<Object?> _toList() {
    return <Object?>[
      id,
      slug,
      title,
      description,
      iconUrl,
      downloads,
      categories,
    ];
  }

  Object encode() {
    return _toList();  }

  static ModrinthProject decode(Object result) {
    result as List<Object?>;
    return ModrinthProject(
      id: result[0]! as String,
      slug: result[1]! as String,
      title: result[2]! as String,
      description: result[3]! as String,
      iconUrl: result[4]! as String,
      downloads: result[5]! as int,
      categories: (result[6]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModrinthProject || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(slug, other.slug) && _deepEquals(title, other.title) && _deepEquals(description, other.description) && _deepEquals(iconUrl, other.iconUrl) && _deepEquals(downloads, other.downloads) && _deepEquals(categories, other.categories);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ModrinthProject(id: $id, slug: $slug, title: $title, description: $description, iconUrl: $iconUrl, downloads: $downloads, categories: $categories)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AccountType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VersionInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is VersionDetail) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AccountInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AuthProgress) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GameConfig) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is GameStatus) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadProgress) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceInfo) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is ModInfo) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is ModrinthProject) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AccountType.values[value];
      case 130:
        return VersionInfo.decode(readValue(buffer)!);
      case 131:
        return VersionDetail.decode(readValue(buffer)!);
      case 132:
        return AccountInfo.decode(readValue(buffer)!);
      case 133:
        return AuthProgress.decode(readValue(buffer)!);
      case 134:
        return GameConfig.decode(readValue(buffer)!);
      case 135:
        return GameStatus.decode(readValue(buffer)!);
      case 136:
        return DownloadProgress.decode(readValue(buffer)!);
      case 137:
        return DeviceInfo.decode(readValue(buffer)!);
      case 138:
        return ModInfo.decode(readValue(buffer)!);
      case 139:
        return ModrinthProject.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LauncherHostApi {
  /// Constructor for [LauncherHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LauncherHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<VersionInfo>> getVersionList() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getVersionList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<VersionInfo>();
  }

  Future<VersionDetail> getVersionDetail(String versionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getVersionDetail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[versionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VersionDetail;
  }

  Future<void> installVersion(String versionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.installVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[versionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AuthProgress> startMicrosoftLogin() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.startMicrosoftLogin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AuthProgress;
  }

  Future<AccountInfo> loginOffline(String username) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.loginOffline$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[username]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AccountInfo;
  }

  Future<void> logout() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.logout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AccountInfo> getCurrentAccount() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getCurrentAccount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AccountInfo;
  }

  Future<List<AccountInfo>> getAccounts() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getAccounts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<AccountInfo>();
  }

  Future<GameStatus> startGame(GameConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.startGame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GameStatus;
  }

  Future<void> stopGame() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.stopGame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<GameStatus> getGameStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getGameStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GameStatus;
  }

  Future<void> injectTouchEvent(double x, double y, int action, int pointerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.injectTouchEvent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[x, y, action, pointerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelDownload(String taskId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.cancelDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[taskId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<DeviceInfo> getDeviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DeviceInfo;
  }

  Future<List<ModInfo>> getInstalledMods(String gameDir, String loaderType) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.getInstalledMods$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[gameDir, loaderType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ModInfo>();
  }

  Future<List<ModrinthProject>> searchModrinth(String query, String mcVersion, String loaderType) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.searchModrinth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[query, mcVersion, loaderType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ModrinthProject>();
  }

  Future<void> installModrinthMod(String projectId, String versionId, String gameDir) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.installModrinthMod$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[projectId, versionId, gameDir]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> toggleMod(String gameDir, String fileName, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.toggleMod$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[gameDir, fileName, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> installModLoader(String versionId, String loaderType, String loaderVersion) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.litelauncher.LauncherHostApi.installModLoader$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[versionId, loaderType, loaderVersion]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class LauncherFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDownloadProgress(DownloadProgress progress);

  void onAuthProgress(AuthProgress progress);

  void onGameStatusChange(GameStatus status);

  void onLog(String line);

  static void setUp(LauncherFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onDownloadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final DownloadProgress arg_progress = args[0]! as DownloadProgress;
          try {
            api.onDownloadProgress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onAuthProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AuthProgress arg_progress = args[0]! as AuthProgress;
          try {
            api.onAuthProgress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onGameStatusChange$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final GameStatus arg_status = args[0]! as GameStatus;
          try {
            api.onGameStatusChange(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onLog$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_line = args[0]! as String;
          try {
            api.onLog(arg_line);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
