// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.litelauncher.app.bridge

@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LauncherApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class AccountType(val raw: Int) {
  MICROSOFT(0),
  OFFLINE(1),
  YGGDRASIL(2);

  companion object {
    fun ofRaw(raw: Int): AccountType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VersionInfo (
  val id: String,
  val type: String,
  val url: String,
  val releaseTime: String,
  val installed: Boolean,
  val loaderName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VersionInfo {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val url = pigeonVar_list[2] as String
      val releaseTime = pigeonVar_list[3] as String
      val installed = pigeonVar_list[4] as Boolean
      val loaderName = pigeonVar_list[5] as String?
      return VersionInfo(id, type, url, releaseTime, installed, loaderName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      url,
      releaseTime,
      installed,
      loaderName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VersionInfo
    return LauncherApiPigeonUtils.deepEquals(this.id, other.id) && LauncherApiPigeonUtils.deepEquals(this.type, other.type) && LauncherApiPigeonUtils.deepEquals(this.url, other.url) && LauncherApiPigeonUtils.deepEquals(this.releaseTime, other.releaseTime) && LauncherApiPigeonUtils.deepEquals(this.installed, other.installed) && LauncherApiPigeonUtils.deepEquals(this.loaderName, other.loaderName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.id)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.type)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.url)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.releaseTime)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.installed)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.loaderName)
    return result
  }
  override fun toString(): String {
    return "VersionInfo(id=$id, type=$type, url=$url, releaseTime=$releaseTime, installed=$installed, loaderName=$loaderName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VersionDetail (
  val id: String,
  val type: String,
  val mainClass: String,
  val assetsIndex: String,
  val javaVersion: Long,
  val releaseTime: String,
  val size: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VersionDetail {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val mainClass = pigeonVar_list[2] as String
      val assetsIndex = pigeonVar_list[3] as String
      val javaVersion = pigeonVar_list[4] as Long
      val releaseTime = pigeonVar_list[5] as String
      val size = pigeonVar_list[6] as Long
      return VersionDetail(id, type, mainClass, assetsIndex, javaVersion, releaseTime, size)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      mainClass,
      assetsIndex,
      javaVersion,
      releaseTime,
      size,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VersionDetail
    return LauncherApiPigeonUtils.deepEquals(this.id, other.id) && LauncherApiPigeonUtils.deepEquals(this.type, other.type) && LauncherApiPigeonUtils.deepEquals(this.mainClass, other.mainClass) && LauncherApiPigeonUtils.deepEquals(this.assetsIndex, other.assetsIndex) && LauncherApiPigeonUtils.deepEquals(this.javaVersion, other.javaVersion) && LauncherApiPigeonUtils.deepEquals(this.releaseTime, other.releaseTime) && LauncherApiPigeonUtils.deepEquals(this.size, other.size)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.id)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.type)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.mainClass)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.assetsIndex)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.javaVersion)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.releaseTime)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.size)
    return result
  }
  override fun toString(): String {
    return "VersionDetail(id=$id, type=$type, mainClass=$mainClass, assetsIndex=$assetsIndex, javaVersion=$javaVersion, releaseTime=$releaseTime, size=$size)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AccountInfo (
  val id: String,
  val username: String,
  val uuid: String,
  val type: AccountType,
  val skinUrl: String? = null,
  val authServer: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AccountInfo {
      val id = pigeonVar_list[0] as String
      val username = pigeonVar_list[1] as String
      val uuid = pigeonVar_list[2] as String
      val type = pigeonVar_list[3] as AccountType
      val skinUrl = pigeonVar_list[4] as String?
      val authServer = pigeonVar_list[5] as String?
      return AccountInfo(id, username, uuid, type, skinUrl, authServer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      username,
      uuid,
      type,
      skinUrl,
      authServer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AccountInfo
    return LauncherApiPigeonUtils.deepEquals(this.id, other.id) && LauncherApiPigeonUtils.deepEquals(this.username, other.username) && LauncherApiPigeonUtils.deepEquals(this.uuid, other.uuid) && LauncherApiPigeonUtils.deepEquals(this.type, other.type) && LauncherApiPigeonUtils.deepEquals(this.skinUrl, other.skinUrl) && LauncherApiPigeonUtils.deepEquals(this.authServer, other.authServer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.id)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.username)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.uuid)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.type)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.skinUrl)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.authServer)
    return result
  }
  override fun toString(): String {
    return "AccountInfo(id=$id, username=$username, uuid=$uuid, type=$type, skinUrl=$skinUrl, authServer=$authServer)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AuthProgress (
  val userCode: String,
  val verificationUri: String,
  val status: String,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthProgress {
      val userCode = pigeonVar_list[0] as String
      val verificationUri = pigeonVar_list[1] as String
      val status = pigeonVar_list[2] as String
      val error = pigeonVar_list[3] as String?
      return AuthProgress(userCode, verificationUri, status, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      userCode,
      verificationUri,
      status,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthProgress
    return LauncherApiPigeonUtils.deepEquals(this.userCode, other.userCode) && LauncherApiPigeonUtils.deepEquals(this.verificationUri, other.verificationUri) && LauncherApiPigeonUtils.deepEquals(this.status, other.status) && LauncherApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.userCode)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.verificationUri)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.status)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "AuthProgress(userCode=$userCode, verificationUri=$verificationUri, status=$status, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GameConfig (
  val versionId: String,
  val gameDir: String,
  val javaHome: String,
  val maxRamMb: Long,
  val renderMode: Long,
  val loaderType: String,
  val extraJvmArgs: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GameConfig {
      val versionId = pigeonVar_list[0] as String
      val gameDir = pigeonVar_list[1] as String
      val javaHome = pigeonVar_list[2] as String
      val maxRamMb = pigeonVar_list[3] as Long
      val renderMode = pigeonVar_list[4] as Long
      val loaderType = pigeonVar_list[5] as String
      val extraJvmArgs = pigeonVar_list[6] as List<String>
      return GameConfig(versionId, gameDir, javaHome, maxRamMb, renderMode, loaderType, extraJvmArgs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      versionId,
      gameDir,
      javaHome,
      maxRamMb,
      renderMode,
      loaderType,
      extraJvmArgs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GameConfig
    return LauncherApiPigeonUtils.deepEquals(this.versionId, other.versionId) && LauncherApiPigeonUtils.deepEquals(this.gameDir, other.gameDir) && LauncherApiPigeonUtils.deepEquals(this.javaHome, other.javaHome) && LauncherApiPigeonUtils.deepEquals(this.maxRamMb, other.maxRamMb) && LauncherApiPigeonUtils.deepEquals(this.renderMode, other.renderMode) && LauncherApiPigeonUtils.deepEquals(this.loaderType, other.loaderType) && LauncherApiPigeonUtils.deepEquals(this.extraJvmArgs, other.extraJvmArgs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.versionId)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.gameDir)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.javaHome)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.maxRamMb)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.renderMode)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.loaderType)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.extraJvmArgs)
    return result
  }
  override fun toString(): String {
    return "GameConfig(versionId=$versionId, gameDir=$gameDir, javaHome=$javaHome, maxRamMb=$maxRamMb, renderMode=$renderMode, loaderType=$loaderType, extraJvmArgs=$extraJvmArgs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GameStatus (
  val state: Long,
  val fps: Long,
  val usedRamMb: Long,
  val crashReport: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GameStatus {
      val state = pigeonVar_list[0] as Long
      val fps = pigeonVar_list[1] as Long
      val usedRamMb = pigeonVar_list[2] as Long
      val crashReport = pigeonVar_list[3] as String?
      return GameStatus(state, fps, usedRamMb, crashReport)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      fps,
      usedRamMb,
      crashReport,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GameStatus
    return LauncherApiPigeonUtils.deepEquals(this.state, other.state) && LauncherApiPigeonUtils.deepEquals(this.fps, other.fps) && LauncherApiPigeonUtils.deepEquals(this.usedRamMb, other.usedRamMb) && LauncherApiPigeonUtils.deepEquals(this.crashReport, other.crashReport)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.state)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.fps)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.usedRamMb)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.crashReport)
    return result
  }
  override fun toString(): String {
    return "GameStatus(state=$state, fps=$fps, usedRamMb=$usedRamMb, crashReport=$crashReport)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadProgress (
  val taskId: String,
  val name: String,
  val progress: Double,
  val downloadedBytes: Long,
  val totalBytes: Long,
  val speedBytesPerSec: Long,
  val status: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadProgress {
      val taskId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val progress = pigeonVar_list[2] as Double
      val downloadedBytes = pigeonVar_list[3] as Long
      val totalBytes = pigeonVar_list[4] as Long
      val speedBytesPerSec = pigeonVar_list[5] as Long
      val status = pigeonVar_list[6] as String
      return DownloadProgress(taskId, name, progress, downloadedBytes, totalBytes, speedBytesPerSec, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      name,
      progress,
      downloadedBytes,
      totalBytes,
      speedBytesPerSec,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadProgress
    return LauncherApiPigeonUtils.deepEquals(this.taskId, other.taskId) && LauncherApiPigeonUtils.deepEquals(this.name, other.name) && LauncherApiPigeonUtils.deepEquals(this.progress, other.progress) && LauncherApiPigeonUtils.deepEquals(this.downloadedBytes, other.downloadedBytes) && LauncherApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && LauncherApiPigeonUtils.deepEquals(this.speedBytesPerSec, other.speedBytesPerSec) && LauncherApiPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.taskId)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.name)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.progress)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.downloadedBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.speedBytesPerSec)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.status)
    return result
  }
  override fun toString(): String {
    return "DownloadProgress(taskId=$taskId, name=$name, progress=$progress, downloadedBytes=$downloadedBytes, totalBytes=$totalBytes, speedBytesPerSec=$speedBytesPerSec, status=$status)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeviceInfo (
  val totalRamMb: Long,
  val availableRamMb: Long,
  val cpuModel: String,
  val coreCount: Long,
  val gpuRenderer: String,
  val deviceTier: Long,
  val isRooted: Boolean,
  val hasKsuModule: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfo {
      val totalRamMb = pigeonVar_list[0] as Long
      val availableRamMb = pigeonVar_list[1] as Long
      val cpuModel = pigeonVar_list[2] as String
      val coreCount = pigeonVar_list[3] as Long
      val gpuRenderer = pigeonVar_list[4] as String
      val deviceTier = pigeonVar_list[5] as Long
      val isRooted = pigeonVar_list[6] as Boolean
      val hasKsuModule = pigeonVar_list[7] as Boolean
      return DeviceInfo(totalRamMb, availableRamMb, cpuModel, coreCount, gpuRenderer, deviceTier, isRooted, hasKsuModule)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalRamMb,
      availableRamMb,
      cpuModel,
      coreCount,
      gpuRenderer,
      deviceTier,
      isRooted,
      hasKsuModule,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceInfo
    return LauncherApiPigeonUtils.deepEquals(this.totalRamMb, other.totalRamMb) && LauncherApiPigeonUtils.deepEquals(this.availableRamMb, other.availableRamMb) && LauncherApiPigeonUtils.deepEquals(this.cpuModel, other.cpuModel) && LauncherApiPigeonUtils.deepEquals(this.coreCount, other.coreCount) && LauncherApiPigeonUtils.deepEquals(this.gpuRenderer, other.gpuRenderer) && LauncherApiPigeonUtils.deepEquals(this.deviceTier, other.deviceTier) && LauncherApiPigeonUtils.deepEquals(this.isRooted, other.isRooted) && LauncherApiPigeonUtils.deepEquals(this.hasKsuModule, other.hasKsuModule)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.totalRamMb)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.availableRamMb)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.cpuModel)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.coreCount)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.gpuRenderer)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.deviceTier)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.isRooted)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.hasKsuModule)
    return result
  }
  override fun toString(): String {
    return "DeviceInfo(totalRamMb=$totalRamMb, availableRamMb=$availableRamMb, cpuModel=$cpuModel, coreCount=$coreCount, gpuRenderer=$gpuRenderer, deviceTier=$deviceTier, isRooted=$isRooted, hasKsuModule=$hasKsuModule)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModInfo (
  val fileName: String,
  val name: String,
  val version: String,
  val loaderType: String,
  val enabled: Boolean,
  val size: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModInfo {
      val fileName = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val version = pigeonVar_list[2] as String
      val loaderType = pigeonVar_list[3] as String
      val enabled = pigeonVar_list[4] as Boolean
      val size = pigeonVar_list[5] as Long
      return ModInfo(fileName, name, version, loaderType, enabled, size)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fileName,
      name,
      version,
      loaderType,
      enabled,
      size,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModInfo
    return LauncherApiPigeonUtils.deepEquals(this.fileName, other.fileName) && LauncherApiPigeonUtils.deepEquals(this.name, other.name) && LauncherApiPigeonUtils.deepEquals(this.version, other.version) && LauncherApiPigeonUtils.deepEquals(this.loaderType, other.loaderType) && LauncherApiPigeonUtils.deepEquals(this.enabled, other.enabled) && LauncherApiPigeonUtils.deepEquals(this.size, other.size)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.fileName)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.name)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.version)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.loaderType)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.enabled)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.size)
    return result
  }
  override fun toString(): String {
    return "ModInfo(fileName=$fileName, name=$name, version=$version, loaderType=$loaderType, enabled=$enabled, size=$size)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModrinthProject (
  val id: String,
  val slug: String,
  val title: String,
  val description: String,
  val iconUrl: String,
  val downloads: Long,
  val categories: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModrinthProject {
      val id = pigeonVar_list[0] as String
      val slug = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val description = pigeonVar_list[3] as String
      val iconUrl = pigeonVar_list[4] as String
      val downloads = pigeonVar_list[5] as Long
      val categories = pigeonVar_list[6] as List<String>
      return ModrinthProject(id, slug, title, description, iconUrl, downloads, categories)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      slug,
      title,
      description,
      iconUrl,
      downloads,
      categories,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModrinthProject
    return LauncherApiPigeonUtils.deepEquals(this.id, other.id) && LauncherApiPigeonUtils.deepEquals(this.slug, other.slug) && LauncherApiPigeonUtils.deepEquals(this.title, other.title) && LauncherApiPigeonUtils.deepEquals(this.description, other.description) && LauncherApiPigeonUtils.deepEquals(this.iconUrl, other.iconUrl) && LauncherApiPigeonUtils.deepEquals(this.downloads, other.downloads) && LauncherApiPigeonUtils.deepEquals(this.categories, other.categories)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.id)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.slug)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.title)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.description)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.iconUrl)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.downloads)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.categories)
    return result
  }
  override fun toString(): String {
    return "ModrinthProject(id=$id, slug=$slug, title=$title, description=$description, iconUrl=$iconUrl, downloads=$downloads, categories=$categories)"
  }
}
private open class LauncherApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AccountType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VersionInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VersionDetail.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccountInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthProgress.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GameConfig.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GameStatus.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadProgress.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfo.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModInfo.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModrinthProject.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AccountType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VersionInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VersionDetail -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AccountInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AuthProgress -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is GameConfig -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is GameStatus -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is DownloadProgress -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is DeviceInfo -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ModInfo -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ModrinthProject -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LauncherHostApi {
  fun getVersionList(callback: (Result<List<VersionInfo>>) -> Unit)
  fun getVersionDetail(versionId: String, callback: (Result<VersionDetail>) -> Unit)
  fun installVersion(versionId: String, callback: (Result<Unit>) -> Unit)
  fun startMicrosoftLogin(callback: (Result<AuthProgress>) -> Unit)
  fun loginOffline(username: String, callback: (Result<AccountInfo>) -> Unit)
  fun logout(callback: (Result<Unit>) -> Unit)
  fun getCurrentAccount(callback: (Result<AccountInfo>) -> Unit)
  fun getAccounts(callback: (Result<List<AccountInfo>>) -> Unit)
  fun startGame(config: GameConfig, callback: (Result<GameStatus>) -> Unit)
  fun stopGame(callback: (Result<Unit>) -> Unit)
  fun getGameStatus(callback: (Result<GameStatus>) -> Unit)
  fun injectTouchEvent(x: Double, y: Double, action: Long, pointerId: Long, callback: (Result<Unit>) -> Unit)
  fun cancelDownload(taskId: String, callback: (Result<Unit>) -> Unit)
  fun getDeviceInfo(callback: (Result<DeviceInfo>) -> Unit)
  fun getInstalledMods(gameDir: String, loaderType: String, callback: (Result<List<ModInfo>>) -> Unit)
  fun searchModrinth(query: String, mcVersion: String, loaderType: String, callback: (Result<List<ModrinthProject>>) -> Unit)
  fun installModrinthMod(projectId: String, versionId: String, gameDir: String, callback: (Result<Unit>) -> Unit)
  fun toggleMod(gameDir: String, fileName: String, enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun installModLoader(versionId: String, loaderType: String, loaderVersion: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by LauncherHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LauncherApiPigeonCodec()
    }
    /** Sets up an instance of `LauncherHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LauncherHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getVersionList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getVersionList{ result: Result<List<VersionInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getVersionDetail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val versionIdArg = args[0] as String
            api.getVersionDetail(versionIdArg) { result: Result<VersionDetail> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.installVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val versionIdArg = args[0] as String
            api.installVersion(versionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.startMicrosoftLogin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startMicrosoftLogin{ result: Result<AuthProgress> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.loginOffline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            api.loginOffline(usernameArg) { result: Result<AccountInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logout{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getCurrentAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCurrentAccount{ result: Result<AccountInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getAccounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAccounts{ result: Result<List<AccountInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.startGame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as GameConfig
            api.startGame(configArg) { result: Result<GameStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.stopGame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopGame{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getGameStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getGameStatus{ result: Result<GameStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.injectTouchEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            val actionArg = args[2] as Long
            val pointerIdArg = args[3] as Long
            api.injectTouchEvent(xArg, yArg, actionArg, pointerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            api.cancelDownload(taskIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceInfo{ result: Result<DeviceInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.getInstalledMods$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val gameDirArg = args[0] as String
            val loaderTypeArg = args[1] as String
            api.getInstalledMods(gameDirArg, loaderTypeArg) { result: Result<List<ModInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.searchModrinth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val mcVersionArg = args[1] as String
            val loaderTypeArg = args[2] as String
            api.searchModrinth(queryArg, mcVersionArg, loaderTypeArg) { result: Result<List<ModrinthProject>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.installModrinthMod$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val projectIdArg = args[0] as String
            val versionIdArg = args[1] as String
            val gameDirArg = args[2] as String
            api.installModrinthMod(projectIdArg, versionIdArg, gameDirArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.toggleMod$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val gameDirArg = args[0] as String
            val fileNameArg = args[1] as String
            val enabledArg = args[2] as Boolean
            api.toggleMod(gameDirArg, fileNameArg, enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.litelauncher.LauncherHostApi.installModLoader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val versionIdArg = args[0] as String
            val loaderTypeArg = args[1] as String
            val loaderVersionArg = args[2] as String
            api.installModLoader(versionIdArg, loaderTypeArg, loaderVersionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LauncherFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LauncherFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LauncherApiPigeonCodec()
    }
  }
  fun onDownloadProgress(progressArg: DownloadProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onDownloadProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LauncherApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAuthProgress(progressArg: AuthProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onAuthProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LauncherApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGameStatusChange(statusArg: GameStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onGameStatusChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LauncherApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onLog(lineArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.litelauncher.LauncherFlutterApi.onLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(lineArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LauncherApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
